pgadmin4:
  container_name: pgadmin4
  build:
    context: ./.templates/pgadmin4/.
    args:
      - DOCKERHUB_TAG=latest
  restart: unless-stopped
  environment:
    TZ: ${TZ:-Etc/UTC}
    PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:?eg echo PGADMIN_DEFAULT_EMAIL=user@your.home.arpa >>~/IOTstack/.env}
    PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:?eg echo PGADMIN_DEFAULT_PASSWORD=somePassword >>~/IOTstack/.env}
  ports:
    - "5050:80"
    - "5051:443"
  volumes:
    - ./volumes/pgadmin4/pgadmin:/var/lib/pgadmin
    - ./volumes/pgadmin4/pgadmin4:/pgadmin4
