rtl_433:
  container_name: rtl_433
  image: hertzg/rtl_433:latest-debian-latest
  depends_on:
    - mosquitto
  environment:
    TZ: ${TZ:-Etc/UTC}
  devices:
    - /dev/bus/usb
  restart: unless-stopped

