octoprint:
  container_name: octoprint
  image: octoprint/octoprint
  restart: unless-stopped
  environment:
    TZ: ${TZ:-Etc/UTC}
  ports:
    - "9980:80"
  devices:
    - "${OCTOPRINT_DEVICE_PATH:?eg echo OCTOPRINT_DEVICE_PATH=/dev/serial0 >>~/IOTstack/.env}:/dev/ttyACM0"
  volumes:
    - ./volumes/octoprint:/octoprint

